/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author denis
 */
public class BookAFlight extends javax.swing.JFrame {

    /**
     * Creates new form BookAFlight
     */
    public BookAFlight() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        faf_lbl = new javax.swing.JLabel();
        onewayb = new javax.swing.JRadioButton();
        roundtripb = new javax.swing.JRadioButton();
        multicityb = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        destinationcb = new javax.swing.JComboBox();
        adultt = new javax.swing.JLabel();
        origincb = new javax.swing.JComboBox();
        childcb = new javax.swing.JComboBox();
        adultcb = new javax.swing.JComboBox();
        origint = new javax.swing.JLabel();
        childt = new javax.swing.JLabel();
        infantt = new javax.swing.JLabel();
        infantcb = new javax.swing.JComboBox();
        searchflightb = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        depart_lbl = new javax.swing.JLabel();
        return_lbl = new javax.swing.JLabel();
        depart_datechooser = new com.toedter.calendar.JDateChooser();
        return_datechooser = new com.toedter.calendar.JDateChooser();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        faf_lbl.setBackground(new java.awt.Color(204, 204, 255));
        faf_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        faf_lbl.setForeground(new java.awt.Color(255, 255, 255));
        faf_lbl.setText("FIND A FLIGHT");
        jPanel1.add(faf_lbl);
        faf_lbl.setBounds(240, 50, 240, 70);

        onewayb.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        onewayb.setForeground(new java.awt.Color(255, 255, 255));
        onewayb.setText("One-way");
        jPanel1.add(onewayb);
        onewayb.setBounds(290, 120, 140, 50);

        roundtripb.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        roundtripb.setForeground(new java.awt.Color(255, 255, 255));
        roundtripb.setText("Round Trip");
        roundtripb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundtripbActionPerformed(evt);
            }
        });
        jPanel1.add(roundtripb);
        roundtripb.setBounds(80, 120, 160, 50);

        multicityb.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        multicityb.setForeground(new java.awt.Color(255, 255, 255));
        multicityb.setText("Multi-City");
        multicityb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multicitybActionPerformed(evt);
            }
        });
        jPanel1.add(multicityb);
        multicityb.setBounds(480, 120, 140, 50);

        jLabel4.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DESTINATION");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(440, 180, 160, 40);

        destinationcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Cebu(CEB)", "Davao(DVO)", "Zamboanga(ZAM)", "Puerto Princesa(PPS)" }));
        jPanel1.add(destinationcb);
        destinationcb.setBounds(470, 220, 210, 40);

        adultt.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        adultt.setForeground(new java.awt.Color(255, 255, 255));
        adultt.setText("ADULT(12+yrs)");
        adultt.setToolTipText("");
        jPanel1.add(adultt);
        adultt.setBounds(50, 360, 170, 30);

        origincb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "MNL-MANILA", "CLK-CLARK" }));
        origincb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origincbActionPerformed(evt);
            }
        });
        jPanel1.add(origincb);
        origincb.setBounds(100, 220, 210, 40);

        childcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jPanel1.add(childcb);
        childcb.setBounds(320, 390, 140, 30);

        adultcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "8", "9" }));
        jPanel1.add(adultcb);
        adultcb.setBounds(80, 390, 140, 30);

        origint.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        origint.setForeground(new java.awt.Color(255, 255, 255));
        origint.setText("ORIGIN");
        jPanel1.add(origint);
        origint.setBounds(80, 180, 90, 40);

        childt.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        childt.setForeground(new java.awt.Color(255, 255, 255));
        childt.setText("CHILD(2-11yrs)");
        jPanel1.add(childt);
        childt.setBounds(290, 360, 170, 31);

        infantt.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        infantt.setForeground(new java.awt.Color(255, 255, 255));
        infantt.setText("INFANT(under 2yrs)");
        jPanel1.add(infantt);
        infantt.setBounds(480, 360, 230, 30);

        infantcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jPanel1.add(infantcb);
        infantcb.setBounds(540, 390, 140, 30);

        searchflightb.setFont(new java.awt.Font("Sitka Heading", 0, 24)); // NOI18N
        searchflightb.setText("SEARCH FLIGHT");
        jPanel1.add(searchflightb);
        searchflightb.setBounds(260, 450, 240, 40);

        title.setFont(new java.awt.Font("Bahnschrift", 0, 48)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("CHING CHONG AIRWAYS");
        jPanel1.add(title);
        title.setBounds(120, 0, 530, 70);

        depart_lbl.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        depart_lbl.setForeground(new java.awt.Color(255, 255, 255));
        depart_lbl.setText("DEPARTURE DATE");
        jPanel1.add(depart_lbl);
        depart_lbl.setBounds(60, 270, 210, 30);

        return_lbl.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        return_lbl.setForeground(new java.awt.Color(255, 255, 255));
        return_lbl.setText("RETURN DATE");
        jPanel1.add(return_lbl);
        return_lbl.setBounds(430, 270, 180, 40);
        jPanel1.add(depart_datechooser);
        depart_datechooser.setBounds(90, 310, 220, 40);
        jPanel1.add(return_datechooser);
        return_datechooser.setBounds(470, 310, 210, 40);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        bg.setText("jLabel1");
        jPanel1.add(bg);
        bg.setBounds(0, -10, 740, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void origincbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origincbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_origincbActionPerformed

    private void roundtripbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundtripbActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_roundtripbActionPerformed

    private void multicitybActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multicitybActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multicitybActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookAFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookAFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookAFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookAFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookAFlight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox adultcb;
    private javax.swing.JLabel adultt;
    private javax.swing.JLabel bg;
    private javax.swing.JComboBox childcb;
    private javax.swing.JLabel childt;
    private com.toedter.calendar.JDateChooser depart_datechooser;
    private javax.swing.JLabel depart_lbl;
    private javax.swing.JComboBox destinationcb;
    private javax.swing.JLabel faf_lbl;
    private javax.swing.JComboBox infantcb;
    private javax.swing.JLabel infantt;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton multicityb;
    private javax.swing.JRadioButton onewayb;
    private javax.swing.JComboBox origincb;
    private javax.swing.JLabel origint;
    private com.toedter.calendar.JDateChooser return_datechooser;
    private javax.swing.JLabel return_lbl;
    private javax.swing.JRadioButton roundtripb;
    private javax.swing.JButton searchflightb;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
