/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PAHIRAM!
 */
public class CustomerDetails extends javax.swing.JFrame {

    /**
     * Creates new form CustomerDetails
     */
    public CustomerDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        custdet_lbl = new javax.swing.JLabel();
        customerId_lbl = new javax.swing.JLabel();
        customername_lbl = new javax.swing.JLabel();
        gender_lbl = new javax.swing.JLabel();
        mmddyy = new javax.swing.JLabel();
        phonenumber_lbl = new javax.swing.JLabel();
        address_lbl = new javax.swing.JLabel();
        customerId_txt = new javax.swing.JTextField();
        cutomername_txt = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        phonenumber_txt = new javax.swing.JTextField();
        address_txt = new javax.swing.JTextField();
        month = new javax.swing.JComboBox();
        day = new javax.swing.JComboBox();
        save_b = new javax.swing.JButton();
        year = new javax.swing.JComboBox();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CHING CHONG AIRWAYS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 0, 530, 70);

        custdet_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        custdet_lbl.setForeground(new java.awt.Color(255, 255, 255));
        custdet_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        custdet_lbl.setText("CUSTOMER DETAILS");
        jPanel1.add(custdet_lbl);
        custdet_lbl.setBounds(280, 70, 240, 29);

        customerId_lbl.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        customerId_lbl.setForeground(new java.awt.Color(255, 255, 255));
        customerId_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerId_lbl.setText("Customer ID");
        jPanel1.add(customerId_lbl);
        customerId_lbl.setBounds(120, 120, 160, 31);

        customername_lbl.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        customername_lbl.setForeground(new java.awt.Color(255, 255, 255));
        customername_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customername_lbl.setText("Customer Name");
        jPanel1.add(customername_lbl);
        customername_lbl.setBounds(90, 180, 200, 31);

        gender_lbl.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        gender_lbl.setForeground(new java.awt.Color(255, 255, 255));
        gender_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gender_lbl.setText("Gender");
        jPanel1.add(gender_lbl);
        gender_lbl.setBounds(190, 230, 90, 31);

        mmddyy.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        mmddyy.setForeground(new java.awt.Color(255, 255, 255));
        mmddyy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mmddyy.setText("MM/DD/YY");
        jPanel1.add(mmddyy);
        mmddyy.setBounds(140, 280, 140, 31);

        phonenumber_lbl.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        phonenumber_lbl.setForeground(new java.awt.Color(255, 255, 255));
        phonenumber_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phonenumber_lbl.setText("Phone Number");
        jPanel1.add(phonenumber_lbl);
        phonenumber_lbl.setBounds(110, 330, 170, 31);

        address_lbl.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        address_lbl.setForeground(new java.awt.Color(255, 255, 255));
        address_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        address_lbl.setText("Address");
        jPanel1.add(address_lbl);
        address_lbl.setBounds(200, 390, 86, 31);

        customerId_txt.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.add(customerId_txt);
        customerId_txt.setBounds(310, 120, 290, 40);

        cutomername_txt.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.add(cutomername_txt);
        cutomername_txt.setBounds(310, 180, 290, 40);

        male.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");
        jPanel1.add(male);
        male.setBounds(310, 230, 110, 31);

        female.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        jPanel1.add(female);
        female.setBounds(500, 230, 100, 30);

        phonenumber_txt.setBackground(new java.awt.Color(240, 240, 240));
        phonenumber_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phonenumber_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenumber_txtActionPerformed(evt);
            }
        });
        jPanel1.add(phonenumber_txt);
        phonenumber_txt.setBounds(320, 330, 280, 40);

        address_txt.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.add(address_txt);
        address_txt.setBounds(320, 390, 280, 40);

        month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "December", "November", "October", "September", "August", "July", "June", "May", "April", "March", "February", "January" }));
        jPanel1.add(month);
        month.setBounds(320, 280, 80, 30);

        day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "31", "30", "29", "28", "27", "26", "25", "24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9", "8", "7", "6", "5", "4", "3", "2", "1" }));
        jPanel1.add(day);
        day.setBounds(430, 280, 70, 30);

        save_b.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        save_b.setForeground(new java.awt.Color(51, 51, 51));
        save_b.setText("SAVE");
        jPanel1.add(save_b);
        save_b.setBounds(410, 450, 110, 39);

        year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000" }));
        jPanel1.add(year);
        year.setBounds(530, 280, 70, 30);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(0, 0, 800, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phonenumber_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenumber_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenumber_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address_lbl;
    private javax.swing.JTextField address_txt;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel custdet_lbl;
    private javax.swing.JLabel customerId_lbl;
    private javax.swing.JTextField customerId_txt;
    private javax.swing.JLabel customername_lbl;
    private javax.swing.JTextField cutomername_txt;
    private javax.swing.JComboBox day;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel gender_lbl;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton male;
    private javax.swing.JLabel mmddyy;
    private javax.swing.JComboBox month;
    private javax.swing.JLabel phonenumber_lbl;
    private javax.swing.JTextField phonenumber_txt;
    private javax.swing.JButton save_b;
    private javax.swing.JComboBox year;
    // End of variables declaration//GEN-END:variables
}
