/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PAHIRAM!
 */
public class FlightStatus extends javax.swing.JFrame {

    /**
     * Creates new form FlightStatus
     */
    public FlightStatus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        flightstatus_lbl = new javax.swing.JLabel();
        prov_lbl = new javax.swing.JLabel();
        airline_lbl = new javax.swing.JLabel();
        depart_lbl = new javax.swing.JLabel();
        arriv_lbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        title.setFont(new java.awt.Font("Bahnschrift", 0, 48)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("CHING CHONG AIRWAYS");
        jPanel1.add(title);
        title.setBounds(120, 10, 530, 70);

        flightstatus_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        flightstatus_lbl.setForeground(new java.awt.Color(255, 255, 255));
        flightstatus_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        flightstatus_lbl.setText("FLIGHT STATUS");
        jPanel1.add(flightstatus_lbl);
        flightstatus_lbl.setBounds(230, 60, 310, 70);

        prov_lbl.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        prov_lbl.setForeground(new java.awt.Color(255, 255, 255));
        prov_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prov_lbl.setText("PROVINCE");
        jPanel1.add(prov_lbl);
        prov_lbl.setBounds(60, 130, 130, 31);

        airline_lbl.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        airline_lbl.setForeground(new java.awt.Color(255, 255, 255));
        airline_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        airline_lbl.setText("AIRLINE");
        jPanel1.add(airline_lbl);
        airline_lbl.setBounds(240, 130, 100, 30);

        depart_lbl.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        depart_lbl.setForeground(new java.awt.Color(255, 255, 255));
        depart_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        depart_lbl.setText("DEPARTURE");
        jPanel1.add(depart_lbl);
        depart_lbl.setBounds(390, 130, 140, 31);

        arriv_lbl.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        arriv_lbl.setForeground(new java.awt.Color(255, 255, 255));
        arriv_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arriv_lbl.setText("ARRIVAL");
        jPanel1.add(arriv_lbl);
        arriv_lbl.setBounds(580, 130, 110, 31);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PROVINCE", "AIRLINE", "DEPARTURE", "ARRIVAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setToolTipText("PROVINCE");
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 180, 800, 350);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        bg.setText("jLabel1");
        jPanel1.add(bg);
        bg.setBounds(0, -37, 800, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlightStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airline_lbl;
    private javax.swing.JLabel arriv_lbl;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel depart_lbl;
    private javax.swing.JLabel flightstatus_lbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel prov_lbl;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
