/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author denis
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        flight = new javax.swing.JButton();
        checkin = new javax.swing.JButton();
        flightstatus = new javax.swing.JButton();
        slogan_lbl = new javax.swing.JLabel();
        admin = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        flight.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        flight.setForeground(new java.awt.Color(51, 51, 51));
        flight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book.png"))); // NOI18N
        flight.setText("Book");
        flight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightActionPerformed(evt);
            }
        });
        jPanel1.add(flight);
        flight.setBounds(80, 200, 170, 70);

        checkin.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        checkin.setForeground(new java.awt.Color(51, 51, 51));
        checkin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/checkin.png"))); // NOI18N
        checkin.setText("Check In");
        checkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinActionPerformed(evt);
            }
        });
        jPanel1.add(checkin);
        checkin.setBounds(310, 200, 170, 70);

        flightstatus.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        flightstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flightstatus.png"))); // NOI18N
        flightstatus.setText("Flight Status");
        flightstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightstatusActionPerformed(evt);
            }
        });
        jPanel1.add(flightstatus);
        flightstatus.setBounds(530, 200, 220, 70);

        slogan_lbl.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        slogan_lbl.setForeground(new java.awt.Color(255, 255, 255));
        slogan_lbl.setText("IT'S TIME TO FLY CHINGCHONGS. FLY HIGH!");
        jPanel1.add(slogan_lbl);
        slogan_lbl.setBounds(230, 120, 370, 30);

        admin.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        admin.setForeground(new java.awt.Color(51, 51, 51));
        admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin.png"))); // NOI18N
        admin.setText("Admin");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        jPanel1.add(admin);
        admin.setBounds(310, 320, 170, 70);

        title.setFont(new java.awt.Font("Bahnschrift", 0, 48)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("CHING CHONG AIRWAYS");
        jPanel1.add(title);
        title.setBounds(150, 50, 530, 90);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(0, 0, 800, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void flightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightActionPerformed
          dispose();
            new BookAFlight().setVisible(true);
    }//GEN-LAST:event_flightActionPerformed

    private void checkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinActionPerformed
          dispose();
            new CheckIn().setVisible(true);
    }//GEN-LAST:event_checkinActionPerformed

    private void flightstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightstatusActionPerformed
          dispose();
            new FlightStatus().setVisible(true);
    }//GEN-LAST:event_flightstatusActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
          dispose();
            new LogIn().setVisible(true);
    }//GEN-LAST:event_adminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin;
    private javax.swing.JLabel bg;
    private javax.swing.JButton checkin;
    private javax.swing.JButton flight;
    private javax.swing.JButton flightstatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel slogan_lbl;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
